name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'geekypandey'
      email:
        description: 'email'
        required: true
        default: 'anuragcarbon1998@gmail.com'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install
        run : | 
          python -m pip install -r requirements.txt
      - name: run file
        run : |
              ./setup.sh
      - name: git push
        run: |
              git config --global user.email "anuragcarbon1998@gmail.com"
              git config --global user.name "geekypandey"
              
              git add -A
              git commit -m 'update data.json'
              git push
        
