on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  say_hello:
    - runs-on: ubuntu-lastest
    - steps:
      - name: Say Hello
        run: echo "Hello!"
