name: CI

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        cc: [gcc, clang]
        curl: [openssl, gnutls, nss]
        kerberos: [libkrb5, heimdal]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Dependencies
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cc }} \
            libcurl4-${{ matrix.curl }}-dev \
            ${{ matrix.kerberos }}-dev
      - if: ${{ matrix.os }} == 'macos-latest'
        name: Install Dependencies
        run: |
          brew install ${{ matrix.cc }} \
            libcurl4-${{ matrix.curl }}-dev \
            ${{ matrix.kerberos }}-dev
      - name: Display Config
        run: |
          echo "C Compiler:"
          ${{ matrix.cc }} --version

          echo ""
          echo "Curl configuration:"
          curl-config --ssl-backends --version

          echo ""
          echo "Kerberos configuration:"
          krb5-config --all
        env:
          CC: ${{ matrix.cc }}
