# This is a basic workflow to help you get started with Actions

name: push on new branch

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Runs a single command using the runners shell
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Get data
        run: |
          ./setup.sh
      - name: Push to develop
        run: |
          git config --global user.email "anuragcarbon1998@gmail.com"
          git config --global user.name "geekypandey"
          git add -A
          git commit -m 'update data.json'
          git push -f https://geekypandey:${{secret.GITHUB_TOKEN}}@github.com/geekypandey/github-action-test.git master:develop

