# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make a commit
      run: |
        echo "hello" >> new_file
        git config --global user.email "anuragcarbon1998@gmail.com"
        git config --global user.name "geekypandey"
        git add -A
        git commit -m 'added new file'
        git push
    - name: Check last commit time
      run: |
        if python check_last_commit.py; then
          echo "New build ready"
        else
          echo "no new build to publish"
        fi
